### ISSUE TITLE
Accessibility - make it possible to use the website without a mouse

### ISSUE THREAD

**Issue by LeoNero** [pennlabs/penn-clubs#11]

**Comment by evakill** [comment]
Not sure how to do this, can you help?

**Comment by LeoNero** [comment]
Users should me able to use the website only with tab, shift and enter keys. A good example is Github.

eslint can help us with that, since eslint-config-airbnb comes with eslint-plugin-jsx-a11y

**Comment by sigmachirality** [comment]
moved to Clubhouse
