### ISSUE TITLE
See how we can improve the interface of some components

### ISSUE THREAD

**Issue by LeoNero** [pennlabs/penn-clubs#17]

**Comment by evakill** [comment]
what do you mean by this?

**Comment by LeoNero** [comment]
By interface I mean the props the components receive.

I added this issue because I think it is a good idea to check if we can simplify or improve the interface of the components

**Comment by sigmachirality** [comment]
Currently props are pretty tight, though it'd be productive to start a discussion on clubhouse/slack on whether to adopt redux, react context, or something else
