### ISSUE TITLE
Authorize payment after confirmation

### ISSUE THREAD

**Issue by rohangpta** [pennlabs/penn-clubs#632]
Use this API with the TTID (transient token id): https://developer.cybersource.com/docs/cybs/en-us/digital-accept-flex/developer/all/rest/digital-accept-flex/da-payments/da-auth-token-task.html

Validate logic after payment success or failure to reclaim state (ticket holds, ticket ownership, confirmation email, etc)

**Comment by julianweng** [comment]
After further discussion today: potentially perform check for tickets existing here (before authorization) versus placing holds on checkout to prevent malicious / repetitive holding of large quantities of tickets. Let me know if this is accurate @anli5005
