### ISSUE TITLE
Create indexes and (optionally) filter on event for tickets

### ISSUE THREAD

**Issue by rohangpta** [pennlabs/penn-clubs#688]
- Create an index on holding expiration and maybe the event to easily filter tickets
- This will make the `update_holds` function substantially cheaper

**Comment by aviupadhyayula** [comment]
Looks like Django creates an index on event [by default](https://stackoverflow.com/questions/5984842/does-django-automatically-generate-indexes-for-foreign-keys-columns), since it's a foreign key.
